### PR TITLE
Don't exit if parsing of /proc/PID/maps fails

### LINKED ISSUE #366: Don't exit if parsing of /proc/PID/maps fails
In `process/parseMappings()` we exit the program if integer conversion functions fail.

For example, in [this line](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/blob/ba327790c06fd35d030646cf6fc284efec56712e/process/process.go#L102) `DecToUint64()` ([code](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/blob/ba327790c06fd35d030646cf6fc284efec56712e/util/util.go#L30)) is called, which exits on failure.

Suggestion: Handle the errors properly, ignore malformed lines and continue.

### PR DESCRIPTION
**Pull request by rockdaboot**
Fixes #366

I believe this is a remnant from old days.
The agent should not exit if there is a parsing error. Instead, log an error and continue with the next line of the maps file.

**Scope**
- treat parsing errors gracefully
- be more consistent with other parsing code and do not `exit()`
- remove unnecessarily exported functions `util.HexToUint64()` and `util.DecToUint64()`
- the formerly exported functions did not document the exiting behavior

**Not in scope**
- dealing with breaking changes of the maps format (assumption is that this won't happen as it will break many different workflows / tools)

### CODE REVIEW

**Comment by christos68k** [comment]
What is assumed failure case here? The `/proc/PID/maps` format is [specified](https://man7.org/linux/man-pages/man5/proc_pid_maps.5.html), so if the agent runs into parsing errors we have to consider the root-cause:

- Is it temporary or will it repeat?
- Is it something that we expect to see once in a while or something exceptional?

If it's temporary and it doesn't repeat then continuing on parsing failures makes sense. If it repeats, then we'll have an agent that keeps running into the issue and continuing and we should probably treat it as a fatal failure and exit.

We should do some research and find out if `/proc/PID/maps` is guaranteed to be consistent on every read. If that's the case then parsing failures to me seem like exceptional fatal failures.

**Comment by rockdaboot** [comment]
> What is assumed failure case here? The `/proc/PID/maps` format is [specified](https://man7.org/linux/man-pages/man5/proc_pid_maps.5.html), so if the agent runs into parsing errors we have to consider the root-cause:
> 
>     * Is it temporary or will it repeat?
> 
>     * Is it something that we expect to see once in a while or something exceptional?
> 
> 
> If it's temporary and it doesn't repeat then continuing on parsing failures makes sense. If it repeats, then we'll have an agent that keeps running into the issue and we should probably treat it as a fatal failure and exit.
> 
> We should do some research and find out if `/proc/PID/maps` is guaranteed to be consistent on every read. If that's the case then parsing failures to me seem like exceptional fatal failures and the fail-safe approach is to exit (and if that's what we decide to do, we need a better approach than `Fatalf` to avoid taking down the OTel collector).

The PR description has been amended to make the purpose of this PR more clear.

Additionally, I don't think it is worth the time to investigate the time for research whether `proc/PID/maps` is "guaranteed to be consistent". Because even if you could "prove" that a certain kernel version has mathematically safe code... code is not set in stone and there could be future changes with subtle regressions or bugs.

A different issue - and not in scope for this PR - is Whether it makes sense or not to detect general breaking changes in the maps files and how to deal with it. IMO, it is not worth the time as a different format breaks all consumers of those files and kernel devs try hard to avoid that.
But even if it happens, and the agent isn't able to read any mapping, the agent still reports this via logging. We currently do not have a metric for this error case, if you look at `SynchronizeProcess()`. We could drop the logs and instead introduce a metric, to avoid spamming of logs.

**Comment by fabled** [comment]
> The agent should not exit if there is a parsing error. Instead, log an error and continue with the next line of the maps file.

I'd just make them debug if any.

But yes, having code removed - especially code that can abort the agent unexpected - is good. Even if technically that code should be unreachable, its better to remove the code.

**Comment by rockdaboot** [comment]
@fabled @christos68k Changed to debug logs and added a metric for parsing/format errors.

File: metrics/ids.go [hunk 1]
```diff
@@ -638,6 +638,9 @@ const (
 	// Number of times a trace event read failed (trace_events)
 	IDTraceEventReadError = 274
 
+	// Number of format errors seen during parsing /proc/<PID>/maps
+	IDErrProcFormat = 275
```
Comment (christos68k) [inline metrics/ids.go:642]:
```suggestion
	IDErrProcParse = 275
```

File: metrics/ids.go [hunk 2]
```diff
@@ -638,6 +638,9 @@ const (
 	// Number of times a trace event read failed (trace_events)
 	IDTraceEventReadError = 274
 
+	// Number of format errors seen during parsing /proc/<PID>/maps
```
Comment (christos68k) [inline metrics/ids.go:641]:
```suggestion
	// Number of parsing errors seen during processing /proc/<PID>/maps
```

File: metrics/metrics.json [hunk 3]
```diff
@@ -1978,5 +1978,12 @@
     "name": "TraceEventReadError",
     "field": "agent.errors.trace_event_read_error",
     "id": 274
+  },
+  {
+    "description": "Number of format errors seen during parsing /proc/<PID>/maps",
+    "type": "counter",
+    "name": "ErrProcFormat",
+    "field": "agent.errors.proc_format",
```
Comment (christos68k) [inline metrics/metrics.json:1986]:
```suggestion
    "description": "Number of parsing errors seen during processing /proc/<PID>/maps",
    "type": "counter",
    "name": "ErrProcParse",
    "field": "agent.errors.proc_parse",
```

File: process/process.go [hunk 4]
```diff
@@ -79,12 +80,13 @@ func trimMappingPath(path string) string {
 	return path
 }
 
-func parseMappings(mapsFile io.Reader) ([]Mapping, error) {
+func parseMappings(mapsFile io.Reader) ([]Mapping, uint32, error) {
+	numFormatErrors := uint32(0)
```
Comment (christos68k) [inline process/process.go:84]:
```suggestion
	numParseErrors := uint32(0)
```

File: process/process.go [hunk 5]
```diff
@@ -11,16 +11,17 @@ import (
 	"fmt"
 	"io"
 	"os"
+	"strconv"
 	"strings"
 	"sync"
 
+	"github.com/sirupsen/logrus"
```
Comment (christos68k) [inline process/process.go:18]: For consistency with the rest of the code

```suggestion
	log "github.com/sirupsen/logrus"
```

File: process/process.go [hunk 6]
```diff
@@ -126,12 +131,31 @@ func parseMappings(mapsFile io.Reader) ([]Mapping, error) {
 		if flags&(elf.PF_R|elf.PF_X) == 0 {
 			continue
 		}
-		inode := util.DecToUint64(fields[4])
+		inode, err := strconv.ParseUint(fields[4], 10, 64)
+		if err != nil {
+			logrus.Debugf("inode: failed to convert %s to uint64: %v", fields[4], err)
```
Comment (christos68k) [inline process/process.go:136]:
```suggestion
			log.Debugf("inode: failed to convert %s to uint64: %v", fields[4], err)
```

File: process/process.go [hunk 7]
```diff
@@ -126,12 +131,31 @@ func parseMappings(mapsFile io.Reader) ([]Mapping, error) {
...
-		device := util.HexToUint64(devs[0])<<8 + util.HexToUint64(devs[1])
+		major, err := strconv.ParseUint(devs[0], 16, 64)
+		if err != nil {
+			logrus.Debugf("major device: failed to convert %s to uint64: %v", devs[0], err)
+			numFormatErrors++
+			continue
+		}
+		minor, err := strconv.ParseUint(devs[1], 16, 64)
+		if err != nil {
+			logrus.Debugf("minor device: failed to convert %s to uint64: %v", devs[0], err)
```
Comment (christos68k) [inline process/process.go:154]:
```suggestion
			logrus.Debugf("minor device: failed to convert %s to uint64: %v", devs[1], err)
```

File: processmanager/manager.go [hunk 8]
```diff
@@ -174,6 +174,8 @@ func collectInterpreterMetrics(ctx context.Context, pm *ProcessManager,
 			metrics.MetricValue(pm.mappingStats.maxProcParseUsec.Swap(0))
 		summary[metrics.IDTotalProcParseUsec] =
 			metrics.MetricValue(pm.mappingStats.totalProcParseUsec.Swap(0))
+		summary[metrics.IDErrProcFormat] =
+			metrics.MetricValue(pm.mappingStats.numProcFormatErrors.Swap(0))
```
Comment (christos68k) [inline processmanager/manager.go:178]:
```suggestion
			metrics.MetricValue(pm.mappingStats.numProcParseErrors.Swap(0))
```

File: processmanager/types.go [hunk 9]
```diff
@@ -72,12 +72,13 @@ type ProcessManager struct {
...
-		numProcAttempts    atomic.Uint32
-		maxProcParseUsec   atomic.Uint32
-		totalProcParseUsec atomic.Uint32
+		errProcNotExist     atomic.Uint32
+		errProcESRCH        atomic.Uint32
+		errProcPerm         atomic.Uint32
+		numProcAttempts     atomic.Uint32
+		maxProcParseUsec    atomic.Uint32
+		totalProcParseUsec  atomic.Uint32
+		numProcFormatErrors atomic.Uint32
```
Comment (christos68k) [inline processmanager/types.go:81]:
```suggestion
		numProcParseErrors atomic.Uint32
```

File: processmanager/processinfo.go [hunk 10]
```diff
@@ -600,8 +600,9 @@ func (pm *ProcessManager) SynchronizeProcess(pr process.Process) {
 
 	pm.mappingStats.numProcAttempts.Add(1)
 	start := time.Now()
-	mappings, err := pr.GetMappings()
+	mappings, numFormatErrors, err := pr.GetMappings()
 	elapsed := time.Since(start)
+	pm.mappingStats.numProcFormatErrors.Add(numFormatErrors)
```
Comment (christos68k) [inline processmanager/processinfo.go:605]:
```suggestion
	pm.mappingStats.numProcParseErrors.Add(numFormatErrors)
```

**Review by florianl — APPROVED** [review]
