### PR TITLE
Fix excessive memory allocation for sched_times (#320)

### LINKED ISSUE #320: Reconsider ebpf map size for off-cpu profiling
### Summary

This has been raised at https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/316#discussion_r1924130492

> Isn't this sizing excessive if we bound it by number of possible PIDs? For example,
> if we set `off-cpu-threshold` to `1000`, we'll end up with a map that takes up roughly 
> `4194304*16 = 64MB` since we pre-allocate. 
>
> Generated off-cpu events are bounded by cores and scheduler call frequency, so for example
> we could size this map as: `next_pow2(cores*1000*pollInterval)` using 1000Hz as an upper
> bound estimate of scheduler call frequency which should consume far less memory.

### PR DESCRIPTION
**Pull request by christos68k**
### Summary

On my 16 core local system (VM, possibleCPUs:128, onlineCPUs:16), the previous logic allocated more than 5GB of kernel memory as worst-case (with `off-cpu-threshold` set to 1000) and the agent took ~20 seconds to start due to swapping.

This PR reduces the worst-case down to 5MB.

Fixes #320.
Also see https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/320#issuecomment-2714207299.

### CODE REVIEW

**Review by gnurizen — APPROVED** [review]

File: tracer/tracer.go [hunk 1]
```diff
@@ -535,26 +535,24 @@ func loadAllMaps(coll *cebpf.CollectionSpec, cfg *Config,
...
-	// sched_times, calculate a size based on some assumptions.
-	// On modern systems /proc/sys/kernel/pid_max defaults to 4194304.
-	// Try to fit this PID space scaled down with cfg.OffCPUThreshold into
-	// this map.
-	adaption["sched_times"] = (4194304 * cfg.OffCPUThreshold) / support.OffCPUThresholdMax
+	// To not lose too many scheduling events but also not oversize sched_times,
+	// calculate a size based on an assumed upper bound of scheduler events per
+	// second (1000hz) multiplied by an average time a task remains off CPU (3s),
+	// scaled by the probability of capturing a trace.
+	adaption["sched_times"] = (4096 * cfg.OffCPUThreshold) / support.OffCPUThresholdMax
```
Comment (rockdaboot) [inline tracer/tracer.go:555]: Not a blocker, but it is not obvious to me how 4096 reflects the mentioned "average time a task remains off CPU (3s)". How exactly has the number 4096 been determined and is this the the best value or does it need further refinement?

**Review by rockdaboot — APPROVED** [review]

File: tracer/tracer.go (hunk 1 above)
Comment (christos68k) [reply tracer/tracer.go:555]: pow2(1000*3)
