### PR TITLE
Delayed processing for ProcessManager.pidToProcessInfo

### LINKED ISSUE #278: Sending executable path for processes that have exited
The solution I implemented in #253 doesn't account for a process exiting while there are still trace events for that process to be processed and reported. If that happens then the executable path retrieval [logic](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/blob/fc0dcae4780c7f010dd4da2435dd884e7aaccacf/processmanager/processinfo.go#L647-L657) will return the empty string and there will be no executable path attribute attached to the profile.

Some possible solutions:

1. Retrieve executable path in the kernel and send it with the trace (same as with `comm`).
2. Delay cleaning up [pidToProcessInfo](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/blob/fc0dcae4780c7f010dd4da2435dd884e7aaccacf/processmanager/types.go#L53-L54) after a PID exit event.
3. Cleanup `pidToProcessInfo` immediately on PID exit, but store `pidToExecutablePath` in a secondary cache. Then do secondary lookups in that cache if the primary lookup in `pidToProcessInfo` fails.

Note that we only care about process exit since there is no race for newly created processes: in order for userspace to receive a trace belonging to a particular PID, `pidToProcessInfo` has to be populated for that PID (therefore the executable path is guaranteed to exist).

Option 3. seems to be the simplest. Option 1. will probably involve walking filesystem datastructures and dealing with `task_struct` without BTF/CO-RE. Option 2. introduces a PID reuse concern (albeit theoretical with current trace poll interval).

If option 3. is chosen then we should probably also decouple executable path storage from `pidToProcessInfo` and just use a single LRU for paths e.g. `pidToExecutableInfo`.

### PR DESCRIPTION
**Pull request by christos68k**
### Summary

- Renamed `SymbolizationComplete` to `ProcessedUntil` and moved to `processinfo.go`
- Dropped no longer needed "symbolize now" remnants
- Implemented delayed `ProcessManager.pidToProcessInfo` cleanup

Leverages #307 to ensure that process metadata is not discarded before all relevant trace events have been processed. 

Fixes #278.

You may find reviewing commit-by-commit to be simpler.

### CODE REVIEW

File: processmanager/processinfo.go [hunk 1]
```diff
@@ -506,32 +506,28 @@ func (pm *ProcessManager) synchronizeMappings(pr process.Process,
...
+		len(pm.interpreters[pid]) > 0) {
+		pm.exitEvents[pid] = exitKTime
+	}
 	if !ok {
 		log.Debugf("Skip process exit handling for unknown PID %d", pid)
-		return symbolize
+		return
 	}
 
 	// Delete all entries we have for this particular PID from pid_page_to_mapping_info.
```
Comment (christos68k) [inline processmanager/processinfo.go:533]: I kept this cleanup here as there's no need to postpone cleaning up the eBPF map until `exitKTime` (unlike `pidToProcessInfo`). This also reduces processing time of `ProcessedUntil`.

File: processmanager/processinfo.go [hunk 2]
```diff
@@ -506,32 +506,28 @@ func (pm *ProcessManager) synchronizeMappings(pr process.Process,
...
-// is stored for later processing in SymbolizationComplete when all traces have been collected.
-// There can be a race condition if we can not clean up the references for this process
+// ProcessPIDExit informs the ProcessManager that a process exited and no longer will be scheduled.
+// exitKTime is stored for later processing in ProcessedUntil, when traces up to this time have been
+// processed. There can be a race condition if we can not clean up the references for this process
 // fast enough and this particular pid is reused again by the system.
 // NOTE: Exported only for tracer.
-func (pm *ProcessManager) ProcessPIDExit(pid libpf.PID) bool {
+func (pm *ProcessManager) ProcessPIDExit(pid libpf.PID) {
+	exitKTime := times.GetKTime()
```
Comment (christos68k) [inline processmanager/processinfo.go:515]: Moved this outside the lock for improved accuracy (there's a debug log in `ProcessedUntil` that prints exit latency).

File: processmanager/processinfo.go [hunk 3]
```diff
@@ -506,32 +507,36 @@ func (pm *ProcessManager) synchronizeMappings(pr process.Process,
...
 	}
-
-	info, ok := pm.pidToProcessInfo[pid]
-	if !ok {
+	if !pidExists {
 		log.Debugf("Skip process exit handling for unknown PID %d", pid)
-		return symbolize
+		return
+	}
+	if pidExited {
```
Comment (christos68k) [inline processmanager/processinfo.go:537]: We don't want to attempt a repeat cleanup for the same PID, if we've previously performed it.

File: processmanager/manager.go [hunk 4]
```diff
@@ -348,34 +347,6 @@ func (pm *ProcessManager) MaybeNotifyAPMAgent(
 	return serviceName
 }
 
-func (pm *ProcessManager) SymbolizationComplete(traceCaptureKTime times.KTime) {
```
Comment (christos68k) [inline processmanager/manager.go:351]: Moved to `processinfo.go` for consistency (all `pidToProcessInfo` accessors in one place) and renamed to `ProcessedUntil`.

File: processmanager/processinfo.go [hunk 5]
```diff
@@ -548,9 +553,6 @@ func (pm *ProcessManager) ProcessPIDExit(pid libpf.PID) bool {
 				address, pid, err)
 		}
 	}
-	delete(pm.pidToProcessInfo, pid)
```
Comment (christos68k) [inline processmanager/processinfo.go:551]: This is now taking place in `ProcessedUntil`, delayed until `traceCaptureKTime >= pidExitKtime`.

File: processmanager/manager.go [hunk 6]
```diff
@@ -294,33 +293,6 @@ func (pm *ProcessManager) ConvertTrace(trace *host.Trace) (newTrace *libpf.Trace
 	return newTrace
 }
 
-// findMappingForTrace locates the mapping for a given host trace.
```
Comment (christos68k) [inline processmanager/manager.go:297]: Moved without changes to `processinfo.go` for [consistency](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/blob/84c6ca880ad4be106a760efb5ab555709f7cce8e/processmanager/processinfo.go#L6-L10).

File: processmanager/processinfo.go [hunk 7]
```diff
@@ -506,32 +507,36 @@ func (pm *ProcessManager) synchronizeMappings(pr process.Process,
...
 	pm.mu.Lock()
 	defer pm.mu.Unlock()
 
-	symbolize := false
-	exitKTime := times.GetKTime()
-	if pm.interpreterTracerEnabled {
-		if len(pm.interpreters[pid]) > 0 {
+	pidExited := false
+	info, pidExists := pm.pidToProcessInfo[pid]
+	if pidExists || (pm.interpreterTracerEnabled &&
```
Comment (christos68k) [inline processmanager/processinfo.go:525]: Essentially same logic as before with these additions:

1. Don't add `exitKTime` to `pm.exitEvents` if it already exists.
2. Also add `exitKTime` to `pm.exitEvents` if `pm.pidToProcessInfo[pid]` exists, as we want to cleanup the latter in delayed fashion.

File: processmanager/processinfo.go [hunk 8]
```diff
@@ -670,3 +672,61 @@ func (pm *ProcessManager) ExePathForPID(pid libpf.PID) string {
...
+	nowKTime := times.GetKTime()
+	log.Debugf("ProcessedUntil captureKT: %v latency: %v ms",
+		traceCaptureKTime, (nowKTime-traceCaptureKTime)/1e6)
+
+	for pid, pidExitKTime := range pm.exitEvents {
+		if pidExitKTime > traceCaptureKTime {
+			continue
+		}
+
+		delete(pm.pidToProcessInfo, pid)
```
Comment (christos68k) [inline processmanager/processinfo.go:716]: Same logic as before with this single-line addition.

File: processmanager/processinfo.go [hunk 9]
```diff
@@ -506,32 +507,36 @@ func (pm *ProcessManager) synchronizeMappings(pr process.Process,
...
+		// for the same PID, don't update exitKTime if we've previously recorded it.
+		if _, pidExited = pm.exitEvents[pid]; !pidExited {
 			pm.exitEvents[pid] = exitKTime
-			symbolize = true
 		}
 	}
-
-	info, ok := pm.pidToProcessInfo[pid]
-	if !ok {
+	if !pidExists {
```
Comment (florianl) [inline processmanager/processinfo.go:533]: To keep the global read & write lock as short as possible, the `if !pidExists {..}` part should be moved before `if pidExists || (pm.interpreterTracerEnabled && len(pm.interpreters[pid]) > 0) {..}`.

File: processmanager/processinfo.go (hunk 3 above)
Comment (florianl) [inline processmanager/processinfo.go:537]: I think, `pidExited` should be renamed to `pidExitProcessed` so something similar, this would it make obvious, that we want to avoid duplicate work.

File: processmanager/processinfo.go [hunk 10]
```diff
@@ -670,3 +672,61 @@ func (pm *ProcessManager) ExePathForPID(pid libpf.PID) string {
...
+}
+
+func (pm *ProcessManager) ProcessedUntil(traceCaptureKTime times.KTime) {
+	pm.mu.Lock()
+	defer pm.mu.Unlock()
+
+	nowKTime := times.GetKTime()
+	log.Debugf("ProcessedUntil captureKT: %v latency: %v ms",
+		traceCaptureKTime, (nowKTime-traceCaptureKTime)/1e6)
+
```
Comment (florianl) [inline processmanager/processinfo.go:710]: keep the lock holding as short as possible:
```suggestion
	nowKTime := times.GetKTime()
	log.Debugf("ProcessedUntil captureKT: %v latency: %v ms",
		traceCaptureKTime, (nowKTime-traceCaptureKTime)/1e6)

	pm.mu.Lock()
	defer pm.mu.Unlock()
```

**Review by florianl — COMMENTED** [review]
first look with some comments

File: processmanager/processinfo.go (hunk 9 above)
Comment (rockdaboot) [reply processmanager/processinfo.go:533]: That would prevent executing `if _, pidExited = ...` in case `(pm.interpreterTracerEnabled && len(pm.interpreters[pid]) > 0` is true.

File: processmanager/processinfo.go [hunk 11]
```diff
@@ -506,32 +507,36 @@ func (pm *ProcessManager) synchronizeMappings(pr process.Process,
...
 // fast enough and this particular pid is reused again by the system.
 // NOTE: Exported only for tracer.
-func (pm *ProcessManager) ProcessPIDExit(pid libpf.PID) bool {
+func (pm *ProcessManager) ProcessPIDExit(pid libpf.PID) {
+	exitKTime := times.GetKTime()
 	log.Debugf("- PID: %v", pid)
 	defer pm.ebpf.RemoveReportedPID(pid)
 
 	pm.mu.Lock()
 	defer pm.mu.Unlock()
```
Comment (rockdaboot) [inline processmanager/processinfo.go:521]: Don't use defer and explicitly lock/unlock to avoid logging inside the critical code section.

File: processmanager/processinfo.go [hunk 12]
```diff
@@ -670,3 +672,61 @@ func (pm *ProcessManager) ExePathForPID(pid libpf.PID) string {
...
+	for pid, pidExitKTime := range pm.exitEvents {
+		if pidExitKTime > traceCaptureKTime {
+			continue
+		}
+
+		delete(pm.pidToProcessInfo, pid)
+
+		for _, instance := range pm.interpreters[pid] {
+			if err := instance.Detach(pm.ebpf, pid); err != nil {
+				log.Errorf("Failed to handle interpreted process exit for PID %d: %v",
```
Comment (rockdaboot) [inline processmanager/processinfo.go:720]: Join these errors and log them after unlocking the mutex.

File: processmanager/processinfo.go [hunk 13]
```diff
@@ -670,3 +672,61 @@ func (pm *ProcessManager) ExePathForPID(pid libpf.PID) string {
...
+					pid, err)
+			}
+		}
+		delete(pm.interpreters, pid)
+		delete(pm.exitEvents, pid)
+
+		log.Debugf("PID %v exit latency %v ms", pid, (nowKTime-pidExitKTime)/1e6)
```
Comment (rockdaboot) [inline processmanager/processinfo.go:727]: Log after unlock()

Comment (christos68k) [reply processmanager/processinfo.go:727]: I agree but let's do this in a new PR to keep the focus of this PR tighter.

File: processmanager/processinfo.go (hunk 12 above)
Comment (christos68k) [reply processmanager/processinfo.go:720]: Same here, let's do this in a new PR.

File: processmanager/processinfo.go (hunk 10 above)
Comment (christos68k) [reply processmanager/processinfo.go:710]: This can affect the latency measurement, since we're timing before the lock.

File: processmanager/processinfo.go (hunk 3 above)
Comment (christos68k) [reply processmanager/processinfo.go:537]: Renamed

File: processmanager/processinfo.go (hunk 9 above)
Comment (christos68k) [reply processmanager/processinfo.go:533]: Like Tim said this would alter the logic. I tried to keep as much of the original semantics the same. Maybe here it's possible to safely say that `if !pidExists` then it's OK not to write `exitKTime` in `pm.exitEvents` but we'd need to carefully examine all subsystem interactions, check for race conditions etc.

**Review by rockdaboot — APPROVED** [review]

**Review by florianl — APPROVED** [review]

File: processmanager/processinfo.go (hunk 9 above)
Comment (florianl) [reply processmanager/processinfo.go:533]: follow up is done in https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/325
